baseURL = "https://jiiiieuuuun.github.io/"
languageCode = "en-us"
title = "기술블로그 TEST 중.."
theme = "startbootstrap-clean-blog"
copyright = "©DKBMC. All rights reserved. Powered by GitHub Pages."

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "DK BMC Devlog Description"
  Author = "DK BMC"
  email = "benoit.benedetti@gmail.com"
  Ganalytics = "XX-00000000-0"
  # This will load all the CSS defined in the list
  # customCSS = ["<absolute path to CSS>", "/static/css/test.css", "<or just load it off the internet>"]

[[params.social]]
    title = "twitter"
    url = "https://twitter.com/humboldtux"
[[params.social]]
    title = "github"
    url = "https://github.com/humboldtux"
[[params.social]]
    title = "facebook"
    url = "https://www.facebook.com/FACEBOOKHANDLE"

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -180